"use client"

import { useState } from "react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Brain, MessageCircle, TrendingUp, Shield } from "lucide-react"
import HealthIQChat from "@/components/services/healthiq-chat"
import { useAuth } from "@/hooks/useAuth"
import { apiClient } from "@/lib/api"

interface HealthIQProps {
  userRole?: string
}

export default function HealthIQIntegrated({ userRole = "patient" }: HealthIQProps) {
  const { token } = useAuth()
  const baseApiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api'
  const healthiqApiUrl = `${baseApiUrl}/healthiq`

  return (
    <div className="space-y-6 sm:space-y-8 p-4 sm:p-6">
      {/* Hero Section */}
      <div className="text-center max-w-4xl mx-auto">
        <div className="flex items-center justify-center mb-4">
          <div className="w-12 h-12 sm:w-16 sm:h-16 bg-primary/20 rounded-2xl flex items-center justify-center">
            <Brain className="w-6 h-6 sm:w-8 sm:h-8 text-primary" />
          </div>
        </div>
        <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-2 sm:mb-4 text-foreground">
          HealthIQ™ AI Assistant
        </h1>
        <p className="text-sm sm:text-base md:text-xl text-muted-foreground max-w-2xl mx-auto px-4">
          Your personal AI health assistant providing intelligent insights, predictive analytics,
          and personalized recommendations while maintaining complete privacy.
        </p>
      </div>

      <Tabs defaultValue="chat" className="space-y-4 sm:space-y-6">
        <TabsList className="grid w-full grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-0">
          <TabsTrigger value="chat" className="text-xs sm:text-sm">
            <MessageCircle className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">AI Chat</span>
            <span className="sm:hidden">Chat</span>
          </TabsTrigger>
          <TabsTrigger value="insights" className="text-xs sm:text-sm">
            <TrendingUp className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Health Insights</span>
            <span className="sm:hidden">Insights</span>
          </TabsTrigger>
          <TabsTrigger value="analytics" className="text-xs sm:text-sm">
            <Brain className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Analytics</span>
            <span className="sm:hidden">Analytics</span>
          </TabsTrigger>
          <TabsTrigger value="privacy" className="text-xs sm:text-sm">
            <Shield className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Privacy</span>
            <span className="sm:hidden">Privacy</span>
          </TabsTrigger>
        </TabsList>

        {/* AI Chat Tab */}
        <TabsContent value="chat" className="space-y-4">
          <HealthIQChat apiUrl={healthiqApiUrl} token={token || undefined} />
        </TabsContent>

        {/* Health Insights Tab */}
        <TabsContent value="insights" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5" />
                Your Health Insights
              </CardTitle>
              <CardDescription>
                AI-generated insights based on your health data and trends
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-center py-8 text-muted-foreground">
                <p className="mb-4">Upload health data through the chat to generate personalized insights</p>
                <p className="text-sm">Insights will appear here as they are generated by our AI system</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Predictive Analytics Tab */}
        <TabsContent value="analytics" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5" />
                Predictive Health Analytics
              </CardTitle>
              <CardDescription>
                AI-powered predictions based on your health trends and risk factors
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-center py-8 text-muted-foreground">
                <p className="mb-4">Predictive analytics will be available once you have sufficient health data</p>
                <p className="text-sm">Our AI analyzes patterns to predict potential health risks and outcomes</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Privacy Dashboard Tab */}
        <TabsContent value="privacy" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="w-5 h-5" />
                Privacy & Data Control
              </CardTitle>
              <CardDescription>
                Manage how your health data is processed and shared
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg">
                  <h3 className="font-semibold text-green-900 dark:text-green-100 mb-2">Privacy Guaranteed</h3>
                  <ul className="text-sm text-green-700 dark:text-green-300 space-y-1">
                    <li>✓ End-to-end encryption for all data</li>
                    <li>✓ AI processing respects your privacy settings</li>
                    <li>✓ Blockchain verification for transparency</li>
                    <li>✓ You control who accesses your insights</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
